### ISSUE TITLE
Enable server side cors

### ISSUE THREAD

**Issue by manoprasanth-m** [avatsaev/webb-tracker-api#32]
I get cors error when I use Fetch. 

"Access to fetch at 'https://api.jwst-hub.com/' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

Also I have included {mode: no-cors}
but it doesn't work

**Comment by avatsaev** [comment]
I'll take a look

**Comment by avatsaev** [comment]
should be fixed, try again.
