### ISSUE TITLE
Public REST API throws 502 Bad Gateway error

### ISSUE THREAD

**Issue by michaelguse** [avatsaev/webb-tracker-api#34]
For the last day the public REST API endpoint for tracking https://api.jwst-hub.com/track results in a 502 Bad Gateway response.

**Comment by mickeydelo** [comment]
I made a little app that just displayed the distance completion in percent full screen with a little progress bar animation.  It's similar to the NASA site, but solely focused on the percentage complete.

I have it running full screen on a bunch of devices and for the last two days as JWST is in the final 10% it's dead...

Can we have an update on the server and/or does anybody know of another source to grab the API?

**Comment by FoamyGuy** [comment]
Has anyone else attempted to run an instance of the server? I'm wondering if the demo instance is just in a bade state ATM. Or if something about the structure of the source page changed and broke the way that the data gets parsed out of it.

**Comment by mickeydelo** [comment]
Looks like it’s back up as I write this

**Comment by michaelguse** [comment]
Looks like it started to partially work again on the 22nd and back to work consistently on the 23rd of Jan. 
Thanks for whatever it took to resolve the issue!
